language: node_js
node_js:
  - "0.12"
  - "iojs"
  - "iojs-v2.4.0"

services:
  - mongodb

before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  - sleep 15
  - mongo --version

script:
  - npm install
  - npm test
